app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    
    
    pass_secure = db.Column(db.String(255))
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
   
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))  

    def __repr__(self):
        return f'User {self.username}'
    
class Pitch(db.Model):
    __tablename__ = 'pitch'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    body = db.Column(db.String(255))
    user = db.Column(db.String(200))
    category = db.Column(db.String(200))
    posted = db.Column(db.DateTime,default = datetime.utcnow)

    def saves_pitch(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_pitch_by_category(cls,category):
        pitch_category = Pitch.query.filter_by(category = category)
        
        return pitch_category
    @classmethod
    def get_user_pitch(cls,uname):
        pitch = Pitch.query.filter_by(user = uname).all()
        
        return pitch
    
    @classmethod
    def get_all_pitches(cls):
        pitch_list = Pitch.query.all()
        return pitch_list
    
class Comment(db.Model):
    __tablename__= 'comment'  
    id = db.Column(db.Integer,primary_key = True)
    
    pitch_id = db.Column(db.Integer)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    comment = db.Column(db.String(255))
    user = db.Column(db.String(255))
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_pitch_comment(cls,id):
        comment = Comment.query.filter_by(pitch_id = id)

        return comment
    
    
    
    

app/main/forms.py
from flask_wtf import  FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
    
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators =[Required()])
    submit = SubmitField('Submit')   
    
class NewPitch(FlaskForm):
    title = StringField('pitch title', validators = [Required()])
    category = SelectField(u'input category', choices = [('business','business'),('games','games'),('music','music'),('tech','tech')])
    body = TextAreaField('write your pitch', validators = [Required()]) 
    submit = SubmitField('Submit')
class CommentForm(FlaskForm):
    comment = TextAreaField('write a comment',validators=[Required()])
    submit = SubmitField('Submit')   
    

app/__init__.py
from flask import Flask
from config import  config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

photos = UploadSet('photos',IMAGES)
def create_app(config_name):

    app = Flask(__name__)


    app.config.from_object(config_options[config_name])
    
    
    
    bootstrap.init_app(app) 
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    mail.init_app(app)
    
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
 
 
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,redirect,url_for,abort,request
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,NewPitch,CommentForm
from .. import db,photos

@main.route('/')
def index():

    '''
    This function  returns the index page and its data
    '''
    title = 'PRIMEPITCH'
    pitches = Pitch.get_all_pitches()
    games = Pitch.get_pitch_by_category("games")
    business = Pitch.get_pitch_by_category("business")
    music = Pitch.get_pitch_by_category("music")
    tech = Pitch.get_pitch_by_category("tech")
    
    return render_template('index.html',title= title,games = games,business = business,music = music,tech = tech)
 
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    pitch = Pitch.get_user_pitch(user.username)
    return render_template('profile/profile.html',pitch = pitch, user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/pitch/new/<uname>' ,methods=["GET",'POST'])
def new_pitch(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = NewPitch()
    if form.validate_on_submit():
        title =form.title.data
        pitch = form.body.data
        category = form.category.data
        
        new_pitch = Pitch(title = title,body = pitch,category = category, user =uname)

        new_pitch.saves_pitch()
        
        return redirect(url_for('main.new_pitch',uname = current_user.username))
    title = "New pitch"
    return render_template('newpitch.html',title = title, new_pitch_form = form, user = user)

@main.route('/pitch/comment/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):
    pitch = Pitch.query.filter_by(id = id ).first()
    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(pitch_id = pitch.id, comment = comment, user = current_user.username)
        new_comment.save_comment()
        return redirect(url_for('.pitch',id = pitch.id))

    title = f'{pitch.pitch_title} comment'
    return render_template('comment.html',title = title, comment_form = form,pitch = pitch)
   
# @main.route('/pitch/<id>')
# def pitch(id):
    # pitch = Pitch.query.filter_by(id = id).first()
    
    # comment = Comment.get_pitch_comment(pitch.id)
    # return render_template('pitch.html',pitch = pitch,comment = comment )
    
@main.route('/categories/<category>', methods=['GET',"POST"])    
def categories(category):
    pitches=Pitch.get_pitch_by_category(category)
    
    return render_template('categories.html',pitches=pitches)

app/templates/base.html
<!DOCTYPE html>
{% extends 'bootstrap/base.html'%}
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> PRIMEPITCH </title>
        {% endif %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Courgette|Kaushan+Script|Marck+Script&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
        <link href="https://www.color-hex.com/" rel="colorscheme">

    </head>
    <style>
           
    
    
    </style>
    <body>
       
            {% block navbar %}
                {% include 'navbar.html' %}
            {% endblock %} 
        {% block content %}  
        {% endblock %}
    </body>
</html>

app/templates/categories.html
{% extends 'base.html' %}

{% block content %}
<style>
        body{
            background-image:url(https://stmed.net/sites/default/files/sci-fi-wallpapers-30855-4429710.jpg);
            background-size:cover;
            background-repeat:no-repeat;
        }
        p{
            color:silver;
            font-size:30px;
            font-family: 'Marck Script', cursive;
            text-align:center;
        }
        #fall{
            color:silver;
            font-size:60px;
            text-align:center;
            font-family: 'Courgette', cursive;
        }
</style>
    <h1 id="fall">Pitches...</h1><br><br>
    {% for pitch in pitches %}
    <body>
    <p>your pitch:{{pitch.body}}</p>
    
    </body>
    {% endfor %}
{% endblock content %}

app/templates/comment.html
{% extends ' base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content%}
<style>
    p{
        color:silver;
        font-size:30px;

    }
    body{
        background-image:url(https://stmed.net/sites/default/files/sci-fi-wallpapers-30855-4429710.jpg);
        background-size:cover;
        background-repeat:no-repeat;
    }
</style>
<body>
    <div class="container">
        <p>write your comment</p>
        {{wtf.quick_form(comment_form)}}
    </div>
</body>
{% endblock%}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Courgette|Kaushan+Script|Marck+Script&display=swap" rel="stylesheet">
     
<body>
    <h1 id="in"> PRIMEPITCH </h1>
    <h5>"Go confidently in the direction of your dreams! Live the life you’ve imagined;  Henry David Thoreau."</h5><br><br>
    <p>THis is basically an app built for you to pich an idea for probably a client or a friend.</p>
    <p>It allows you to also leave a comment and choose from an array of diffrent categorys.</p>
    <p>So feel free and try our app!!</p>
<style>

        h1{
            text-align: center;
            color:gray;
            font-size: 75px;
            font-family: 'Courgette', cursive;
        }
        h5{
            font-size:31px;
            color:#990000;
            text-align:center;
            font-family: 'Marck Script', cursive;
        }
        p{
            font-size:25px;
            color:silver;
            text-align:center;
            font-family: 'Kaushan Script', cursive;
        }
        body{
            background-image:url(https://stmed.net/sites/default/files/sci-fi-wallpapers-30855-4429710.jpg);
            background-size:cover;
            background-repeat:no-repeat;

        }
        h2{
            color:#005900;
            font-size:43px;
            font-family: 'Courgette', cursive;
            text-align:center;
        }
        
        a{
            color:red;
            width:100px;
            height:40px;
        }
        h3{
            color:white;
            font-family: 'Bree Serif', serif;
            
        }
        .card{
            background-color:grey;
            height:380px;
            width:250px;
        }
        .card p{
            color:black;
        }
</style>
<div class="container">
    <h2>Categories....</h2><br>
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <h3>The gaming life...</h3>
                <p>Click below to offer your opinion on games and pitch a game idea and revolutionize gaming</p>
                <p>"It is in games that many men discover their paradise.by Robert Wilson Lynd"</p>
                <a class="btn btn-danger" type="button" href="/categories/games" >Games</a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <h3>A maney maker mind...</h3>
                <p>Click below to give your best ideas on business or even tips on how to make ones business successful</p>
                <p>“Have the end in mind and every day make sure your working towards it” – Ryan Allis</p>
                <a class="btn btn-danger" type="button" href="/categories/business" >Business</a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <h3>The food for the soul....</h3>
                <p>Click below to air out your take on music or even give us your ideal genre </p>
                <p>“Music is to the soul what words are to the mind.” ― Modest Mouse</p>
                <a class="btn btn-danger" type="button" href="/categories/music" >Music</a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <h3>For the skillful mind....</h3>
                <p>Click below to express your views on technology and how it affects the human race pitch your idea on how to better it.</p>
                <p>“It's still magic even if you know how it's done.”― Terry Pratchett</p>
                <a class="btn btn-danger" type="button" href="/categories/tech" >Tech</a>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock%}








   

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation </span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="font-family: 'Bree Serif', serif;">PRIMEPITCH</a>
        </div><br>
        <div  class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href = "/pitch/new/{{current_user.username}}">add pitch</a></li>
                    <li><a href="{{url_for('main.update_profile',uname=current_user.username)}}">My profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    {% endif %}
                </ul>
        </div>
     </div>   
</div>

app/templates/newpitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content%}
<style>
         body{
            background-image:url(https://stmed.net/sites/default/files/sci-fi-wallpapers-30855-4429710.jpg);
            background-size:cover;
            background-repeat:no-repeat;

        }
        p{
            color:silver;
            font-size:30px;
            font-family: 'Marck Script', cursive;
            text-align:center;
        }

</style>
<body>
    <div class="container">
        <p>Add pitch</p>
        {{wtf.quick_form(new_pitch_form)}}
    </div>
</body>
{% endblock%}

app/templates/pitch.html
{% extends 'base.html'%}
{% block content%}
    <div class = "row">
        <div class="card">
            <p style="color:silver;">{{pitch.title}}<p>
            <p style="color:silver;">{{pitch.body}}
        </div>
        
    </div>
    <button><a href="/pitch/comment/new/{{pitch.id}}">add comment</a></button>

    <div class="row">
        {% for cmnt in comment%}
            <p style="color:silver;">{{cmnt.comment}}</p>
            <p style="color:silver;">posted by::{{cmnt.user}} on :: {{cmnt.posted}}
        {% endfor%}
    </div>
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<link href="https://fonts.googleapis.com/css?family=Bree+Serif|Courgette|Kaushan+Script|Marck+Script&display=swap" rel="stylesheet">
<body style="background-image:url(https://stmed.net/sites/default/files/sci-fi-wallpapers-30855-4429710.jpg);background-size:cover;background-repeat:no-repeat;">
<div class="container">

<div class="row">

  <div class="col-md-4" style="color:silver;font-family: 'Courgette', cursive">
    <h3 style="font-size:50px;" >Username: {{user.username| capitalize}} 🤑</h3><br><br>

   
    {% if user.bio %}
      <p style="font-size:30px;">Bio :" {{user.bio}} "</p>
    {% else%}
      <p style="font-size:32px;" > {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div><br><br>
<div class="col-md-4"></div>

  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="photo from file" class="img-thumbnail">

    {% else %}
    <p style="font-size:18px;color:gray;">No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_profile',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required >
      <input type="submit">
    </form>
      {% endif %}
  </div>

</div>
</div><br><br>

<p  style="font-size:50px;color:bray;text-align:center;"> Your pitch</p><br><br>
<div class = "row">
  {% for pit in pitch%}
  <div class="col-md-4">
    <div class="card">
      <p  style="font-size:15px;color:white;text-align:center;">Title:{{pit.title}}</p>
      <p  style="font-size:15px;color:white;text-align:center;"> Pitch:{{pit.body}}</p>
    </div>

  </div>
  {% endfor%}
</div>

</body>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}